name: 'Release Cleanup workflow'

on:
  workflow_dispatch:
  push:
  release:

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 1
          keep-old-minor-releases: true
          keep-old-minor-releases-by: 'minor'
